title: Szürke Dániel
<img src="./profile.jpg" alt="Profilkép" width="150">
description: Önéletrajz
show_downloads: false
logo: ./profile.jpg
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
